# ALIYUN

ALIYUN_ACCESS_KEY = 'LTAIhyoEGh8D8nKF'

ALIYUN_ACCESS_SECRET = 'oKAp6XTEFpV81NLFCs3ot7ucLxrLfj'


# ALIYUN OSS
OSS_ACCESS_ENDPOINT = 'oss-cn-qingdao.aliyuncs.com'

# OSS_ACCESS_ENDPOINT = 'vip.tangsuanradio.com'

OSS_ACCESS_KEY_ID = ALIYUN_ACCESS_KEY

OSS_SECRET_ACCESS_KEY = ALIYUN_ACCESS_SECRET

# BUCKET NAME

OSS_STORAGE_BUCKET_NAME = 'tscast'

OSS_DEFAULT_ACL = 'public-read'
